baseURL = "https://ygnmhdtt.github.io"
languageCode = "en-us"
title = "title"
theme = "kiss"
copyright = "(c) ygnmhdtt"
disqusShortname = "shortname"
Paginate = 5
enableRobotsTXT = true

[permalinks]
post = "/:year/:month/:day/:filename"

[params.info]
homeTitle = "ygnmhdtt" # Title for home page

[taxonomies]
tag ="tags"
