baseURL = "http://test.github.io"
languageCode = "en-us"
title = "ygnmhdtt_test"
theme = "kiss"
copyright = "(c) ygnmhdtt"
disqusShortname = "shortname"
Paginate = 4
enableRobotsTXT = true
publishDir = "docs"

[permalinks]
post = "/:year/:month/:day/:filename"

[params.info]
homeTitle = "ygnmhdtt" # Title for home page

[taxonomies]
tag ="tags"
